from app.Controllers.Controller import Controller
from .Auth.LoginController import LoginController
from .Auth.RegisterController import RegisterController
from .Controller import Controller
from .DashboardController import DashboardController
from .TasksController import TasksController
from .TagsController import TagsController
from .GuildsController import GuildsController
from .CyclesController import CyclesController